### PR TITLE
Update to wlroots 0.17

### PR DESCRIPTION
**Pull request by shtirlic**
Bump go,go.mod and to latest wlroots 0.17 release
syms update

PS

I am testing with gles and vulkan renderer (WLR_RENDERER=vulkan) on wayland backend 

image

### CODE REVIEW

**Review by alexbakker — APPROVED** [review]
Thanks. Will merge this when wlroots 0.17 is released.

**Comment by mstarongithub** [comment]
Could you merge this please? wlroots 0.17 got released 3 days ago and I'd love to use this module for a really dumb idea of mine

**Review by alexbakker — CHANGES_REQUESTED** [review]
I'm getting the following error when trying to run tinywl:

```
> go run github.com/swaywm/go-wlroots/cmd/tinywl
# github.com/swaywm/go-wlroots/wlroots
wlroots/wlroots.go:378:2: could not determine kind of name for C.wlr_xcursor_manager_set_cursor_image
```

**Comment by shtirlic** [comment]
Updated to current wlroots and it's working again

**Review by alexbakker — APPROVED** [review]
This became pretty hard to review with all of the unrelated changes. Anyway, seems to work.

Thanks!

**Pull request merged**
